polySphere -r 1;
sets -name "set1";
loadPlugin heather;
string $loader = `createNode heatherImage`;
setAttr -type "string" ($loader + ".depthImage") "E:/public/snotlout_ya_defaultHighRigRN.0109.exr";

string $loader1 = `createNode heatherImage`;
setAttr -type "string" ($loader1 + ".depthImage") "E:/public/hiccup_ya_defaultHighRigRN.0109.exr";

string $dummy = `createNode transform`;
string $heath = `createNode heatherNode`;
setAttr ($heath + ".template") 1;

connectAttr -f ($loader + ".outValue") ($heath + ".inImage[0]");
connectAttr -f ($loader1 + ".outValue") ($heath + ".inImage[1]");

connectAttr -f ($heath + ".outValue") ($dummy + ".tx");

setAttr -type "string" ($heath + ".blockSet") "set1";

