#ifndef BVH_DEFINE_H
#define BVH_DEFINE_H

#define BVHSOLVER_DBG_DRAW 1
// #define BVHSOLVER_DBG_DRAW_LEAFBOX 0
#define BVHSOLVER_DBG_DRAW_LEAFHASH 0
#define BVHSOLVER_DBG_DRAW_BOX 0
#define BVHSOLVER_DBG_DRAW_INTERNALBOX_TO_LEVEL 0
// #define BVHSOLVER_DBG_DRAW_RAY 0
#endif        //  #ifndef BVH_DEFINE_H

