global proc testHarm()
{
string $sphere[] = `polyPlane -ch off -o on -w 32 -h 32 -sw 32 -sh 32`;
int $nv = 1089;
select -r $sphere[0];
pickWalk -d down;
string $mesh[] = `ls -sl -l`;
string $msh = $mesh[0];
print("work on "+$msh);
addAttr -dt doubleArray -ln asanchor -sn aa $msh;
addAttr -dt doubleArray -ln asvalue -sn av $msh;

int $anchorIds[] = {34, 64, 1020, 992, 647};
float $anchorValue[] = {1.0, 0.1, 0.5, 0.8, 0.4};

string $saa = "", $sav ="";
int $i;

float $allaa[], $allav[];
for($i = 0; $i < $nv; $i++) {

    $allaa[$i] = 0;
    
    $allav[$i] = 0;
}

for($i = 0; $i < size($anchorIds); $i++) {
    int $ai = $anchorIds[$i];
    $allaa[$ai] = 1;
    
    $allav[$ai] = $anchorValue[$i];
}

for($i = 0; $i < $nv; $i++) {

    $saa = $saa + " " + $allaa[$i];
    
    $sav = $sav + " " + $allav[$i];
}

string $cmd;

$cmd = "setAttr " + $msh+ ".aa -type doubleArray " + $nv + " " + $saa;

eval($cmd);
$cmd = "setAttr " + $msh+ ".av -type doubleArray " + $nv + " " + $sav;
eval($cmd);

calcHarmCoord -a aa -v av $msh;
}
