MESSAGE (" find aphid libraries ")

if (WIN32)
SET (APHID_FOUND_LIBRARY ${APHID_DIR}/lib/aphidFoundation.lib)
SET (APHID_MATH_LIBRARY ${APHID_DIR}/lib/aphidMath.lib)
    SET (APHID_GEOM_LIBRARY ${APHID_DIR}/lib/aphidGeom.lib)
    SET (APHID_H5_LIBRARY ${APHID_DIR}/lib/aphidH5.lib)
    SET (APHID_UI_LIBRARY ${APHID_DIR}/lib/aphidUI.lib)
    SET (APHID_KD_LIBRARY ${APHID_DIR}/lib/aphidKd.lib)
    SET (APHID_SDB_LIBRARY ${APHID_DIR}/lib/aphidSdb.lib)
    SET (APHID_GRAPH_LIBRARY ${APHID_DIR}/lib/aphidGraph.lib)
set (APHID_TOPO_LIBRARY ${APHID_DIR}/lib/aphidTopology.lib)
set (APHID_OGL_LIBRARY ${APHID_DIR}/lib/aphidOgl.lib)
set (APHID_TTG_LIBRARY ${APHID_DIR}/lib/aphidTtg.lib)
set (APHID_IMG_LIBRARY ${APHID_DIR}/lib/aphidImg.lib)

ELSEIF (APPLE)
SET (APHID_FOUND_LIBRARY ${APHID_DIR}/lib/libaphidFoundation.a)
    set (APHID_MATH_LIBRARY ${APHID_DIR}/lib/libaphidMath.a)
    set (APHID_GEOM_LIBRARY ${APHID_DIR}/lib/libaphidGeom.a)
    set (APHID_H5_LIBRARY ${APHID_DIR}/lib/libaphidH5.a)
    set (APHID_UI_LIBRARY ${APHID_DIR}/lib/libaphidUI.a)
    set (APHID_KD_LIBRARY ${APHID_DIR}/lib/libaphidKd.a)
    set (APHID_SDB_LIBRARY ${APHID_DIR}/lib/libaphidSdb.a)
    set (APHID_GRAPH_LIBRARY ${APHID_DIR}/lib/libaphidGraph.a)
set (APHID_TOPO_LIBRARY ${APHID_DIR}/lib/libaphidTopology.a)
set (APHID_OGL_LIBRARY ${APHID_DIR}/lib/libaphidOgl.a)
set (APHID_TTG_LIBRARY ${APHID_DIR}/lib/libaphidTtg.a)
set (APHID_IMG_LIBRARY ${APHID_DIR}/lib/libaphidImg.a)

ELSEIF (UNIX)
SET (APHID_FOUND_LIBRARY ${APHID_DIR}/lib/libaphidFoundation.so)
    SET (APHID_MATH_LIBRARY ${APHID_DIR}/lib/libaphidMath.so)
    SET (APHID_GEOM_LIBRARY ${APHID_DIR}/lib/libaphidGeom.so)
    SET (APHID_H5_LIBRARY ${APHID_DIR}/lib/libaphidH5.so)
    SET (APHID_UI_LIBRARY ${APHID_DIR}/lib/libaphidUI.so)
    SET (APHID_KD_LIBRARY ${APHID_DIR}/lib/libaphidKd.so)
    SET (APHID_SDB_LIBRARY ${APHID_DIR}/lib/libaphidSdb.so)
    SET (APHID_GRAPH_LIBRARY ${APHID_DIR}/lib/libaphidGraph.so)
set (APHID_TOPO_LIBRARY ${APHID_DIR}/lib/libaphidTopology.so)
set (APHID_OGL_LIBRARY ${APHID_DIR}/lib/libaphidOgl.so)
set (APHID_TTG_LIBRARY ${APHID_DIR}/lib/libaphidTtg.so)
set (APHID_IMG_LIBRARY ${APHID_DIR}/lib/libaphidImg.so)

endif ()

message (" foundation is " ${APHID_FOUND_LIBRARY})
message (" math is " ${APHID_MATH_LIBRARY})
message (" geom is " ${APHID_GEOM_LIBRARY})
message (" h5 is " ${APHID_H5_LIBRARY})
message (" ui is " ${APHID_UI_LIBRARY})
message (" kd is " ${APHID_KD_LIBRARY})
message (" sdb is " ${APHID_SDB_LIBRARY})
message (" graph is " ${APHID_GRAPH_LIBRARY})
message (" topo is " ${APHID_TOPO_LIBRARY})
message (" ogl is " ${APHID_OGL_LIBRARY})
message (" ttg is " ${APHID_TTG_LIBRARY})
